spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#      - id: customer-service
#        uri: lb://customer-service
#        predicates:
#        - Path=/api/customer/**
#        filters:
#        - RewritePath=/api/customer/(?<path>.*),/${path}
#      - id: account-service
#        uri: lb://account-service
#        predicates:
#        - Path=/api/account/**
#        filters:
#        - RewritePath=/api/account/(?<path>.*),/${path}
#      - id: loan-service
#        uri: lb://loan-service
#        predicates:
#        - Path=/api/loan/**
#        filters:
#        - RewritePath=/api/loan/(?<path>.*),/${path}


          
      
server:
  port: 8080
  

