# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mahendra-shinde/cloud-config-demo
server:
  port: 8888
eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: true
